# Generated by Django 5.0.4 on 2024-04-28 23:49

import Electronics_App.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers.', regex='^\\d+$'), Electronics_App.models.validate_not_blank])),
                ('Admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
