# Generated by Django 5.0.4 on 2024-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='electronics_app/static/img'),
        ),
    ]
