# Generated by Django 5.0.4 on 2024-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_app', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=100),
        ),
    ]
