# Generated by Django 5.0.4 on 2024-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0004_remove_customer_address_remove_customer_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
