# Generated by Django 5.0.4 on 2024-05-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0005_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
