# Generated by Django 5.0.4 on 2024-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0007_contain_quantity_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
