# Generated by Django 5.0.4 on 2024-05-03 18:21

import Electronics_App.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0008_product_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_id', models.UUIDField(default=uuid.UUID('9f9f94f8-aeea-4951-b194-f771a1221a84'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(default='', primary_key=True, serialize=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('phone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers.', regex='^\\d+$'), Electronics_App.models.validate_not_blank])),
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('cash_balance', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='update',
            name='customer',
        ),
        migrations.AddField(
            model_name='update',
            name='remaining_quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='update',
            name='sold_quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='update',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Electronics_App.seller'),
        ),
    ]
