# Generated by Django 5.0.4 on 2024-05-03 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0009_cart_category_seller_delete_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('41cca92b-672f-495d-9c5a-3af8db3c682d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='remaining_quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='update',
            name='sold_quantity',
            field=models.IntegerField(default=None),
        ),
    ]
