# Generated by Django 5.0.4 on 2024-05-03 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0011_alter_cart_cart_id_alter_update_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('bdd51f1a-a4ee-4a99-94a2-e785710b24fc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
