# Generated by Django 5.0.4 on 2024-05-03 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0013_alter_cart_cart_id_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('229c93e1-98e2-4ec6-be3b-c65831d7a2bc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
