# Generated by Django 5.0.4 on 2024-05-03 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0015_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('a39b1ff6-5316-4279-ab5c-e277b67cec8a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
