# Generated by Django 5.0.4 on 2024-05-03 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0017_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='remaining_quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('be2234fb-9e45-4450-86e0-93c90d39d965'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
