# Generated by Django 5.0.4 on 2024-05-03 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0018_remove_update_remaining_quantity_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='remaining_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('bf6a88ef-1b70-480e-82ed-ac83f5f5bb2b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
