# Generated by Django 5.0.4 on 2024-05-03 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0019_update_remaining_quantity_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='remaining_quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('ef5ac812-42c2-4f54-98c0-7fe14926508d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
