# Generated by Django 5.0.4 on 2024-05-03 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0020_remove_update_remaining_quantity_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='remaining_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('fcfba72f-17c2-4a7c-be98-fb34db48c354'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
