# Generated by Django 5.0.4 on 2024-05-03 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0023_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('85f6e04c-cffd-464b-9883-fb8fbf3dbd10'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
