# Generated by Django 5.0.4 on 2024-05-03 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0024_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Electronics_App.cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.UUIDField(default=uuid.UUID('a9d6188d-a47c-4a8b-a665-ec39ff7c16da'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
