# Generated by Django 5.0.4 on 2024-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0025_remove_cart_product_product_cart_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
