# Generated by Django 5.0.4 on 2024-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics_App', '0026_remove_product_cart_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='remaining_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
